GST-69 Add forced subtitles support according to automatic subtitle selection feature
castlabs/gst-ttml-subtitles pull request #2
Opened 2022-06-23 11:52 UTC by noneimb

This is the part of the https://github.com/castlabs/gstreamer_asl/pull/21

Added:
- forced subtitles support according to automatic subtitle selection feature

2022-06-23 12:41 UTC, roman380 requested changes
Some naming suggestions and code accuracy; subtitles is something we revisit from time to time so the idea is that we name and comment so that we quickly refresh ourselves and get a correct model

2022-06-23 12:41 UTC, roman380 commented on gst/parser/SubtitleParserUtils.h
> +		bool isDisplayOnlyForced = false;
Maybe let's drop "is" here, `displayOnlyForced` bool would reflect `kSubtitleDisplayModeOnlyForced ` mode from https://castlabs.atlassian.net/wiki/spaces/CD/pages/2986606593/Automatic+Subtitle+Selection+Preferred+text+language Maybe I'd even go with `forcedOnly`. 

Also I'd suggest to rename class from `ScenesHandler` to `SceneHandler` as "smoother language".

2022-06-23 12:41 UTC, roman380 commented on gst/parser/gstttmlparse.cpp
> +    GST_BUFFER_FLAG_ONLY_FORCED_TEXT = GstBufferFlags::GST_BUFFER_FLAG_LAST << 1,
Let's comment this because the definition of forced subs is a bit ambigous in first place. Do we expect this flag to come on entire buffer with 0+ text items and when marked we are to treat all parsed cues as forced? If so, let's just state it in the comment.

Also there can't be "only" on the buffer, no? Whether to display forced only is a user preference: if he decides to not have any subs, there can be some forced, and so in "forced only" mode we'd show only those parsed out with "forced" markup.

Unless I am wrong with reasoning above the flag might be `GST_BUFFER_FLAG_FORCED_TEXT` or alike.

2022-06-23 12:41 UTC, roman380 commented on gst/parser/gstttmlparse.cpp
> +    if (ttmlParser.Parse(self->textbuf->str, timedText::SubtitlesFormat::TTML, GST_BUFFER_FLAG_IS_SET(buf, GST_BUFFER_FLAG_ONLY_FORCED_TEXT)) == CLC_FAIL) {
So here we'd basically propagate buffer's "forced" attribute to individual cues coming out of the buffer?

2022-06-23 12:44 UTC, roman380 commented
> It's extension for build-in GstBufferFlags and has code duplication in downstream gsl plugin. I'm not sure how to properly share this with gsl plugin without code duplication. Perhaps it's better to think about it during GST-60 restructuring.

Can we pull `GstBufferFlagsCustom` into `.h` and `#include` from higher level code?

Also let's rename the enum to better mimic how it's done in the framework, e.g.

```
typedef enum {
  GST_RTP_BUFFER_FLAG_RETRANSMISSION = (GST_BUFFER_FLAG_LAST << 0),
  GST_RTP_BUFFER_FLAG_REDUNDANT      = (GST_BUFFER_FLAG_LAST << 1),
  GST_RTP_BUFFER_FLAG_LAST           = (GST_BUFFER_FLAG_LAST << 8)
} GstRTPBufferFlags;
```

Maybe `GstTtmlBufferFlags`

2022-06-23 14:54 UTC, noneimb commented on gst/parser/gstttmlparse.cpp
> +    GST_BUFFER_FLAG_ONLY_FORCED_TEXT = GstBufferFlags::GST_BUFFER_FLAG_LAST << 1,
@roman380 That's a good proposition to add a comment in code to make it clear.
As defined here https://castlabs.atlassian.net/wiki/spaces/CD/pages/2986606593/Automatic+Subtitle+Selection+Preferred+text+language#Requirements
We have three modes:
1. Do not show automatically ANY subtitles
2. Automatically show ONLY forced
3. Automatically show ALL subtitles

GST_BUFFER_FLAG_ONLY_FORCED_TEXT is responsible for 2nd option, if not set then we go with 3rd option. 1st option was handled by downstream plugin, but as you suggested about this feature design(and I actually agree) this implementation wasn't a good idea. Let's get back to this conversation after new changes if necessary.

2022-06-23 14:57 UTC, noneimb commented on gst/parser/gstttmlparse.cpp
> +    if (ttmlParser.Parse(self->textbuf->str, timedText::SubtitlesFormat::TTML, GST_BUFFER_FLAG_IS_SET(buf, GST_BUFFER_FLAG_ONLY_FORCED_TEXT)) == CLC_FAIL) {
@roman380 I'm not completely sure what you mean, but this option mean "show only forced cues".

2022-06-26 12:51 UTC, roman380 requested changes
AFAIU mostly cleanup comments. One another question: did you think what would be the effect of changing "forced only" on the go?

2022-06-26 12:51 UTC, roman380 commented on gst/parser/SubtitleParser.h
> +		std::vector<GstBuffer*> getSubtitleList() { return sceneHandler->getScenesBuffersList(); }
This is really a nitpick, but also a good example. Use of plural in naming is quite often confusing. There it's three times: scenes, buffers and then list again assumes a collection of something. Since it's not really a heap of unsorted pointers, and it's a list of buffers related to scenes, I believe the name could be more accurate. 

Than after all it's a `std::vector` and not `std::list`. IMO it could be `getSceneBuffers` or `getSceneBufferVector`. In our CL libraries I thnik naming more leans to the former (even though I'd prefer the latter).

2022-06-26 12:51 UTC, roman380 commented on gst/parser/gstttmlparse.cpp
> +          "Skip all subtitles with no forced flag", FALSE,
Maybe a better definition would be "Do not display subttitles unless they are marked as forced". IMO it better follows the mood of our original spec: we have a language preference and hence the subtitle track but the choice is to have subs off.

2022-06-26 12:51 UTC, roman380 commented on gst/parser/gstttmlparse.cpp
> +        GST_DEBUG_OBJECT(object, "video framerate set to %s\n",
wrong copy/pasted string; also since it's for debugging I'd go with %d or whatever the GStreamer helper macro for format is, just for compactness of code

2022-06-26 12:51 UTC, roman380 commented on gst/parser/gstttmlparse.cpp
> +    GST_BUFFER_FLAG_ONLY_FORCED_TEXT = GstBufferFlags::GST_BUFFER_FLAG_LAST << 1,
Thsi entire enum can be deleted now, right? It's unused.

2022-06-26 13:15 UTC, noneimb commented on gst/parser/SubtitleParser.h
> +		std::vector<GstBuffer*> getSubtitleList() { return sceneHandler->getScenesBuffersList(); }
@roman380 It makes sense. Then also `getSubtitles` instead of `getSubtitleList`?

2022-06-26 14:22 UTC, noneimb commented
> AFAIU mostly cleanup comments. One another question: did you think what would be the effect of changing "forced only" on the go?

It'll show forced subtitles, but no guarantee it'll be for preferred language, then it's not right. We probably should use some states. Do you know how to do it better in the simplest form but acceptable?

2022-06-26 14:30 UTC, roman380 approved these changes
:+1: looks good, one tiny comment if you'd want to check before merging

2022-06-26 14:30 UTC, roman380 commented on gst/parser/gstttmlparse.cpp
> +    for (int subtitleIndex = 0; subtitleIndex < subtitles.size(); ++subtitleIndex) {
int -> size_t

2022-06-26 14:30 UTC, roman380 commented on gst/parser/SubtitleParser.h
> +		std::vector<GstBuffer*> getSubtitleList() { return sceneHandler->getScenesBuffersList(); }
Yes, sure

2022-06-26 15:05 UTC, merged